# Generated by Django 4.1.4 on 2022-12-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='episode',
            fields=[
                ('episode_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('episode_name', models.CharField(max_length=255)),
                ('episode_no', models.CharField(max_length=50)),
                ('episode_filepath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('words_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='most_used_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patterns', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('definition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='registerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=11)),
                ('repeat_password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('season_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=255)),
                ('season_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('series_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='words',
            fields=[
                ('words_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('episode_id', models.IntegerField()),
                ('word', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('translation', models.CharField(max_length=255)),
            ],
        ),
    ]
