# Generated by Django 4.1.4 on 2022-12-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_img',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
