# Generated by Django 4.1.4 on 2022-12-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_series_series_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_img',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
